samba:
  image: joebiellik/samba-server

  volumes:
    # You must provide a Samba config file
    - ./smb.conf:/config/smb.conf

    # Shares
    - ~/projects:/mnt/projects
    - ~/videos:/mnt/videos:ro

  ports:
    - "137:137/udp"
    - "138:138/udp"
    - "139:139/tcp"
    - "445:445/tcp"

  environment:
    - USERNAME=joe
    - PASSWORD=samba

    # Defaults
    - UID=1000
    - GID=1000
    - GROUP=samba
    - CONFIG=/config/smb.conf
    
  deploy:
    replicas: 6
    update_config:
      parallelism: 2
      delay: 10s
    restart_policy:
      condition: on-failure